### ISSUE TITLE
Parameter Learn in Live broken

### ISSUE THREAD

**Issue by JaniKervinen** [AURAPluginsLtd/Access-Virus-Editor#25]
legacy reported issue:

Parameters can be learned in Live when Editor is initialized, but as soon as there is a patch loaded to part, parameters can no longer be learned.

**Comment by andreymosin** [comment]
No, parameters can not be learn at all. Namely Automation in ableton doesn't work at all. 
Mac
3.0.0.9024
 Both AU and VST

**Comment by JaniKervinen** [comment]
This should be fixed with latest build 9013. If issue is still persisting, re-open the issue.
