### ISSUE TITLE
A way to update the state of "one part" from hardware (rather than just "all parts")

### ISSUE THREAD

**Issue by Guod3** [AURAPluginsLtd/Access-Virus-Editor#30]
**The problem is:** when using hw control surfaces and sw devices that send CC, PolyAT, Sysex to modify a part on the synth, the state of the part needs to be sent to VirusHE to update the session for total recall. 
The feature "SYNC DATA From HW" works **but takes 16x longer** than is typically required.

**Describe the solution you'd like**
A quick and easy way to **Sync a single chosen** part would be ideal. This could be a small button on each part of the mixer and librarian page parts list. A pulldown menu to select part for sync would probably work as well.

**Comment by JaniKervinen** [comment]
Great idea - What do you think if we change the front panel "sync data from hw" button to act so that when multimode mixer view is on, button will request multi, globals and all parts, but when individual part view mode is on, it would request just a single part data?

**Comment by JaniKervinen** [comment]
Awesome, we shall do that then!

**Comment by Guod3** [comment]
Great, let me know if I can alpha test and provide feedback.
