### ISSUE TITLE
Swap part data, Duplicate part data (retaining original midi channel numbers in the part slots)

### ISSUE THREAD

**Issue by Guod3** [AURAPluginsLtd/Access-Virus-Editor#32]
**Problem:** This feature (requested) is expected to streamline and improve some aspects of typical workflow.

**Duplicate a part**
User would selected a (source) part, then activate an action "duplicate to part" and select a (destination) part slot. 
This action would result in all data (all part info including edit buffer patch, except channel number) to be copied from source to destination multi part slot.
**Why Duplicate?**
This allows for very quick setup of a variation, or alternative part in a DAW session arrangement. The duplicate can be edited  not just the patch but output routing and other settings available in the mixer view. Also, by changing the midi channel of the duplicate to be the same as the source, powerful "unison" type setups would be easily constructed.

**Swap two parts**
User would select a part, then activate an action "swap with part" and select a (destination) part slot. This would result in patch and all data for the two slots to be exchanged (maintaining the original channel numbers in the part slots ).
**Why swap?**
This allows very quick A/B/C variation comparison of sound design for a part including patch, fx send, output routing. 

**Currently**
AFAIK Duplicating a part involves saving the patch to a bank, setting up the duplicate part channel loading the patch into the duplicate part from the saved version.
Currently swapping is probably most easily done by exchanging the actual midi channels settings for both parts.

**Additional context**
Usually far less than 16 parts are actually used. This means there is a lot of redundant info presented to the user from the GUI. Having the actions to easily consolidate what parts are in use to the first 2..5 (or whatever) slots makes things a lot nicer for the brain to deal with. Also, the ability to swap gives users the ability to reorganise the layout of the multi as the arrangement develops (e.g "basses", "leads", "pads" can be grouped together) making things more coherent. 

In this feature request "patch" refers to the current state of the multi part edit buffer.

**Comment by JaniKervinen** [comment]
Hi,

Thanks for the suggestion, but how about this?

https://user-images.githubusercontent.com/46903303/208229501-ab9f9589-2943-400c-87b2-6b9411decd5d.mp4

**Comment by JaniKervinen** [comment]
Swap feature is missing, but copy and paste is already available.

**Comment by Guod3** [comment]
Thanks for pointing this out!
The Utilities/ "Copy Part Data" and "Paste Part Data" are really good to have and indeed allow for the various use cases in the request.
I've noticed that "Part Data" is only a subset (that I can tell..). It includes only Patch, Pan, and FX send levels. (btw: pan knob moves into the pasted position but does not change until you adjust the knob a little).

Can I propose a change to the current action menu:
Utilities/Copy Part Patch  (just the part patch)
Utilities/Copy Part Data    (**All** settings for the multi part, excluding the patch)
Utilities/ Paste     (whatever has been copied)
I feel this is simple but very flexible, and not complicated to understand.

**Comment by JaniKervinen** [comment]
> I've noticed that "Part Data" is only a subset (that I can tell..). It includes only Patch, Pan, and FX send levels. (btw: pan knob moves into the pasted position but does not change until you adjust the knob a little).

Ok, I have to look into this a bit further to fix it.

> Can I propose a change to the current action menu: 
> Utilities/Copy Part Patch (just the part patch) 
> Utilities/Copy Part Data (**All** settings for the multi part, excluding the patch) 
> Utilities/ Paste (whatever has been copied) 
> I feel this is simple but very flexible, and not complicated to understand.

Agree. I will add this in.
