### ISSUE TITLE
Graphical Osc Wave table ( UI )

### ISSUE THREAD

**Issue by Avishayhz** [AURAPluginsLtd/Access-Virus-Editor#36]
There is no way to see the wave tables and Osc morphing 

**Describe the solution you'd like 
I would like to see the Osc shape while selecting and the change when using PW or shape changes to wavetables 

**Describe alternatives you've considered**
Real time Oscilloscop,
Name changing in the parameter display, what now is wave 1, 2 etc. Would be .. bell, sine, pulse  While morphing sine 20% saw 80% etc ..

**Comment by JaniKervinen** [comment]
Not sure if I can pull this off. I tried to attach the wavetable images once, that I can do, but not the realtime thing as it requires some hi-tech stuff beyond my knowledge.

**Comment by Avishayhz** [comment]
Mybe then just the names
...

**Comment by Avishayhz** [comment]
Mybe then just name them

**Comment by Avishayhz** [comment]
I'm closing the issues, this works exactly like the plugin

**Comment by Avishayhz** [comment]
Feature is already implemented
