### ISSUE TITLE
VirusHE Arpeggiator Mode problem

### ISSUE THREAD

**Issue by citysoundman** [AURAPluginsLtd/Access-Virus-Editor#48]
I'm using a Virus B module, and using VirusHE 3.0.0 build 9024 as a standalone app (not plugin). Mac OSX 10.14.
When I'm editing the arpeggiator, there are 7 modes: Off, Up, Down, Up&Down etc. When I select a mode it actually selects a different one than chosen. Off seems to select Up, Up selects Down, Down selects Up& Down, so it looks like it's selecting the next mode after the one chosen.
Also, Apreggiator Patter number 49 is shown as 59, must be a typo.

**Comment by JaniKervinen** [comment]
is this still happening with build 9028 which is available now? (full version - demo is still at 9024)

**Comment by citysoundman** [comment]
Yes, I just installed 9028, the arp mode selection is not correct.

**Comment by JaniKervinen** [comment]
ok going to take a look into this for next build

**Comment by citysoundman** [comment]
great thank you!

**Comment by citysoundman** [comment]
Fixed!! much appreciated :)
