### ISSUE TITLE
HiDPI Display scaling issue

### ISSUE THREAD

**Issue by JaniKervinen** [AURAPluginsLtd/Access-Virus-Editor#5]
legacy reported issue:

Hi,
I got a new monitor which runs in HiDPI mode. That means it has a native resolution of 1600x1200 and I run it with macOS in 1920x1200 (with a small black bar on the top and the bottom). Every application and plugin looks very good on it, except the nice Virus plugin - as AU plugin, but also in Standalone version. It looks like that on the monitor:

<img width="1538" alt="2022-05-26-um-19-41-07" src="https://user-images.githubusercontent.com/46903303/207301254-024e4c2a-d6b3-41cb-9ba5-5d0f51032f7f.png">

On my internal iMac display all is fine. As soon I drag it on the external monitor it is broken. Any idea?! Thanks for your help!

**Comment by JaniKervinen** [comment]
@masc4ii what display is that secondary display of yours? I want to create similar environment regarding settings you have to reproduce this on our end.

**Comment by masc4ii** [comment]
@JaniKervinen it is a NEC 1600x1200 DVI display, connected via external USB2.0 graphics card to my iMac2011. The iMac has just one display output. In my setup I use 2 external monitors:
- Main: Logic
- 2nd (USB2.0): Plugins
- 3rd (MiniDVI): TV for video

The only possibility to get 2 external displays on this old iMac is to use a USB 2.0 graphics card. I got it for around 35€.

https://i-tec.pro/en/produkt/usb2hdtrio-2/

And in general this works by far better than expected. The driver of this graphics card offers HiDPI mode, so you can send higher resolution to the display then it has pixels (all is displayed a bit smaller then). 
I think, macOS does the same if you connect via AirPlay - at least in macOS it looks like you connected an AirPlay device. Technically macOS offers a virtual screen, records the frames, compresses the frames, sends them (via USB or AirPlay WiFi) and the real device will uncompress and show the frames.

VirusHE is the only plugin I use which shows me this bug on this display. If I move the plugin to the monitor, switch the plugin into controllers mode and finally back to graphics mode, all is displayed fine - until next move onto another monitor, project load, or plugin hide/show.

**Comment by JaniKervinen** [comment]
@masc4ii that was interesting to learn about the external display adapter via USB hah!

OK I have to dig into this further more to see what is happening - Definitely needs a fix

**Comment by JaniKervinen** [comment]
@masc4ii I will do a special build for you which will log everything because I can not reproduce this on our end with multiple displays connected. Every resolution I tried worked fine. Ok? Can you shoot me an email to support@auraplugins.com with this issue mentioned so I can share the installer with you?

**Comment by masc4ii** [comment]
@JaniKervinen You got a mail.

**Comment by masc4ii** [comment]
Bump. Did you get my mail? I would like to help solving this bug!

**Comment by JaniKervinen** [comment]
@masc4ii I did, however, I am not able to reproduce it on my end so I will make a special dev build for you that logs the window scaling changes - all you have to do is to send back the log file after dragging the editor to the new window and closing it down.

**Comment by masc4ii** [comment]
I like to do this for you. Waiting for your dev build! 😄

**Comment by masc4ii** [comment]
I tried your test build on my iMac on macOS 10.13. As expected the plugin crashes directly on startup. This machine has no metal support - seems we need the openGL version.
For my MacBook with M1 CPU and BigSur, I now found a driver for this USB graphics adapter. It uses a newer driver version which seems to work completely different. Here HiDPI settings aren't offered - I can select between the resolutions offered by the monitor. So the issue is not visible here. Unfortunately this driver version is just for BigSur and later.

**Comment by JaniKervinen** [comment]
hi @masc4ii I tried several weeks to build the system around it so that it would detect the screen size and then have it forced to different scale but since I don't have that monitor setup like yours, I can't proceed any further. My MacBook Pro display works fine and so does the 4K tv and display I have hooked up.

**Comment by masc4ii** [comment]
@JaniKervinen can't wait to try out what you built! 😄

**Comment by masc4ii** [comment]
I noticed a new behavior:
When the plugin looks like in screenshot on the top of the issue, resizing helps to redraw it correctly. Dragging bigger needs longer, while dragging smaller instantly corrects the UI.

**Comment by masc4ii** [comment]
v9033 crashes on startup:

```
Process:               Access Virus Editor [29179]
Path:                  /Applications/AURA Plugins/Access Virus Editor.app/Contents/MacOS/Access Virus Editor
Identifier:            com.AURAPlugins.app.AccessVirusEditor
Version:               3.0.0.9033 (3.0.0.9033)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Access Virus Editor [29179]
User ID:               501

Date/Time:             2023-03-25 11:47:07.072 +0100
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        0DF537D7-4663-B0E2-3421-A625D0BC6F42

Sleep/Wake UUID:       74914E5C-48A0-463A-8558-4C82A4B22D6F

Time Awake Since Boot: 31000 seconds
Time Since Wake:       27 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000022a8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x22a8:
--> 
    __TEXT                 000000010b763000-000000010ba3f000 [ 2928K] r-x/r-x SM=COW  /Applications/AURA Plugins/Access Virus Editor.app/Contents/MacOS/Access Virus Editor

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.AURAPlugins.app.AccessVirusEditor	0x000000010b7cc684 nvgCreateFontFaceMem + 4
1   com.AURAPlugins.app.AccessVirusEditor	0x000000010b9b6db9 iplug::igraphics::IGraphicsNanoVG::LoadAPIFont(char const*, std::__1::unique_ptr<iplug::igraphics::PlatformFont, std::__1::default_delete<iplug::igraphics::PlatformFont> > const&) + 169
2   com.AURAPlugins.app.AccessVirusEditor	0x000000010b8d52f0 iplug::igraphics::IGraphics::LoadFont(char const*, char const*) + 64
3   com.AURAPlugins.app.AccessVirusEditor	0x000000010b8fbae0 VirusEditor::VirusEditor(iplug::InstanceInfo const&)::$_1::operator()(iplug::igraphics::IGraphics*) const + 752
4   com.AURAPlugins.app.AccessVirusEditor	0x000000010b8afa22 iplug::igraphics::IGEditorDelegate::LayoutUI(iplug::igraphics::IGraphics*) + 34
5   com.AURAPlugins.app.AccessVirusEditor	0x000000010b9b1c12 iplug::igraphics::IGraphicsMac::OpenWindow(void*) + 242
6   com.AURAPlugins.app.AccessVirusEditor	0x000000010b8aa80c iplug::IPlugAPPHost::OpenWindow(HWND__*) + 12
7   com.AURAPlugins.app.AccessVirusEditor	0x000000010b9517a0 iplug::IPlugAPPHost::MainDlgProc(HWND__*, unsigned int, unsigned long, long) + 176
8   com.AURAPlugins.app.AccessVirusEditor	0x000000010b805a8a -[Swell_vVirusEditor_hwnd initChild:Parent:dlgProc:Param:] + 1754
9   com.AURAPlugins.app.AccessVirusEditor	0x000000010b80bf42 -[Swell_vVirusEditor_modelesswindow initModeless:Parent:dlgProc:Param:outputHwnd:forceStyles:] + 658
10  com.AURAPlugins.app.AccessVirusEditor	0x000000010b80d63e SWELL_CreateDialog(SWELL_DialogResourceIndex*, char const*, HWND__*, long (*)(HWND__*, unsigned int, unsigned long, long), long) + 414
11  com.AURAPlugins.app.AccessVirusEditor	0x000000010b99cecf SWELLAppMain + 1039
12  com.apple.CoreFoundation      	0x00007fff2d83939c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
13  com.apple.CoreFoundation      	0x00007fff2d83926a _CFXRegistrationPost + 458
14  com.apple.CoreFoundation      	0x00007fff2d838fa1 ___CFXNotificationPost_block_invoke + 225
15  com.apple.CoreFoundation      	0x00007fff2d7f7b32 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
16  com.apple.CoreFoundation      	0x00007fff2d7f6bc3 _CFXNotificationPost + 659
17  com.apple.Foundation          	0x00007fff2f925047 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
18  com.apple.AppKit              	0x00007fff2aee3206 -[NSApplication _postDidFinishNotification] + 313
19  com.apple.AppKit              	0x00007fff2aee2e4f -[NSApplication _sendFinishLaunchingNotification] + 220
20  com.apple.AppKit              	0x00007fff2adb5a7b -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 562
21  com.apple.AppKit              	0x00007fff2adb56b1 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 690
22  com.apple.Foundation          	0x00007fff2f967ef4 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 287
23  com.apple.Foundation          	0x00007fff2f967d72 _NSAppleEventManagerGenericHandler + 102
24  com.apple.AE                  	0x00007fff2e93ff08 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 1788
25  com.apple.AE                  	0x00007fff2e93f7af dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 41
26  com.apple.AE                  	0x00007fff2e93f69d aeProcessAppleEvent + 383
27  com.apple.HIToolbox           	0x00007fff2cb134a0 AEProcessAppleEvent + 55
28  com.apple.AppKit              	0x00007fff2adb0cfa _DPSNextEvent + 2788
29  com.apple.AppKit              	0x00007fff2b546e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
30  com.apple.AppKit              	0x00007fff2ada584d -[NSApplication run] + 764
31  com.apple.AppKit              	0x00007fff2ad74a3a NSApplicationMain + 804
32  libdyld.dylib                 	0x00007fff5581c015 start + 1
```

Probably it is because you just support Metal. Older Macs don't support Metal. Any chance to get a non-Metal version again? Why Metal is needed at all for a AU plugin?! For video processing I would understand...

**Comment by JaniKervinen** [comment]
I've added new button in top left corner to "minimize" the view. If you are on discord, you have seen it there already :) Coming up in next release
