### ISSUE TITLE
Audio unit failed to load - app crashes. MacOS 12.6.2

### ISSUE THREAD

**Issue by Kodedweb** [AURAPluginsLtd/Access-Virus-Editor#51]
**Describe the bug**
I installed the latest build AccessVirusEditor-v3.0.0-build-9028 onto my M1 MBP running 12.6.2 following a successful demo test. I purchased the license ready to authorize it—both the standalone app and plugin crash when trying to load. The crash report is attached when booting the app; the plugin within Ableton shows an error (audio unit failed to load) with a screen attached.
I noticed that the build numbers differ for the demo and full installer. The demo loads and works fine, but the later complete build fails.

**To Reproduce**
Steps to reproduce the behaviour:
1. Double-click the app icon
2. It fails to load and crashes
3. Drag the plugin to a mini channel in Ableton
4. Audio unit fails to load

**Expected behaviour**
The app loads!

**Screenshots / Videos**
Attached

**Setup Details (please complete the following information):**
 - Computer Model: [MacBook Pro M1 Pro 16" Late 2021]
 - OS: [macOS 12.6.2 (Monterey)]
 - DAW: [Live]
 - MIDI Interface: [USB Midi Virus TI]
 - Synth Model: [Access Virus TI2 Polar]
 - Editor Version: [e.g. 3.0.0 build 9028]
 - Main Connection: [e.g. MIDI, USB]

![Screenshot 2023-03-01 at 18 36 08](https://user-images.git
[crash report.docx](https://github.com/AURAPluginsLtd/Access-Virus-Editor/files/10864301/crash.report.docx)
hubusercontent.com/44868400/222233702-bc58ae95-4f9c-4b66-85b0-d46fc21e5c9d.png)

**Comment by Kodedweb** [comment]
I have removed the app and reinstalled 3 times. 
Also just followed the advice on this https://github.com/AURAPluginsLtd/Access-Virus-Editor/issues/49#issuecomment-1448557166 link, and it still fails to load.

**Comment by mwbhtx** [comment]
Same issue.

My Setup Details:

    Computer Model: MacBook Pro M1 Pro 13" Late 2020
    OS: macOS 13.1 (Ventura)
    DAW: Live
    MIDI Interface: USB Midi Virus TI
    Synth Model: Access Virus TI2 Desktop
    Editor Version: 3.0.0 build 9028
    Main Connection: USB

**Comment by Kodedweb** [comment]
> Same issue. Standlone fails to load (crash dialog popup), AU component fails to load. Haven't tried the demo version.
> 
> My Setup Details:
> 
> ```
> Computer Model: MacBook Pro M1 Pro 13" Late 2020
> OS: macOS 13.1 (Ventura)
> DAW: Live
> MIDI Interface: USB Midi Virus TI
> Synth Model: Access Virus TI2 Desktop
> Editor Version: 3.0.0 build 9028
> Main Connection: USB
> ```

Well, that rules out my next move, which was to install Ventura. I'm disappointed as it's build-related, but no way to download previous versions.

**Comment by mwbhtx** [comment]
> > Same issue. Standlone fails to load (crash dialog popup), AU component fails to load. Haven't tried the demo version.
> > My Setup Details:
> > ```
> > Computer Model: MacBook Pro M1 Pro 13" Late 2020
> > OS: macOS 13.1 (Ventura)
> > DAW: Live
> > MIDI Interface: USB Midi Virus TI
> > Synth Model: Access Virus TI2 Desktop
> > Editor Version: 3.0.0 build 9028
> > Main Connection: USB
> > ```
> 
> Well, that rules out my next move, which was to install Ventura. I'm disappointed as it's build-related, but no way to download previous versions.

I follow instructions in similar thread to run command `brew install libssh2 ` in terminal. This got me working, albeit now I have a graphical UI bug, but it’s loading.

**Comment by Kodedweb** [comment]
> > > Same issue. Standlone fails to load (crash dialog popup), AU component fails to load. Haven't tried the demo version.
> > > My Setup Details:
> > > ```
> > > Computer Model: MacBook Pro M1 Pro 13" Late 2020
> > > OS: macOS 13.1 (Ventura)
> > > DAW: Live
> > > MIDI Interface: USB Midi Virus TI
> > > Synth Model: Access Virus TI2 Desktop
> > > Editor Version: 3.0.0 build 9028
> > > Main Connection: USB
> > > ```
> > 
> > 
> > Well, that rules out my next move, which was to install Ventura. I'm disappointed as it's build-related, but no way to download previous versions.
> 
> I follow instructions in similar thread to run command `brew install libssh2 ` in terminal. This got me working, albeit now I have a graphical UI bug, but it’s loading.

Yup, I also tried that. I ran it using some instructions I found online and went through the whole install process, and my plugin still failed to load. It is frustrating, given I have paid for the full version, and it doesn't work from installation!

**Comment by JaniKervinen** [comment]
fix is on the way. worked fine on our end, so can't predict if it works in real-world scenarios. build 9024 is again behind the normal full download link and build 9028 is under downloads page (but due to being buggy, don't use it).

**Comment by Kodedweb** [comment]
> fix is on the way. worked fine on our end, so can't predict if it works in real-world scenarios. build 9024 is again behind the normal full download link and build 9028 is under downloads page (but due to being buggy, don't use it).

Thanks, that's great. I will install it and see how I get on.
