### ISSUE TITLE
Interface not displaying patch names within patch librarian and can't load external banks

### ISSUE THREAD

**Issue by Kodedweb** [AURAPluginsLtd/Access-Virus-Editor#52]
**Describe the bug**
I finally managed to get the full version working following the earlier build being added for download - thanks!
I have an issue where the plugin is working and outputting sound, but the patch librarian won't display patch names; it looks blank. I have tried the various skins, but that patch librarian window is static, and nothing changes.
I have a screenshot and took a quick video to show what I see. Any advice is welcome, as I am close now to being able to make music again on the Virus!
NOTE. The patch name is displayed on the left panel and also on the mock LCD screen.

I am also unable to load in external sound banks. I select load bank, and nothing happens; no prompt to navigate to the folder.

**To Reproduce**
1.Load the plugin
2. Select patch librarian
3. View list and update 
4. Nothing shows

**Expected behavior**
I expect to see all the patch names as per the screen shots in the manual.

**Screenshots / Videos**
[Attached](https://user-images.githubusercontent.com/44868400/222842273-cc3adfe3-5906-4fa8-86bf-61a962846c33.mp4)
[Screenshot 2023-03-03 at 22 18 09](https://user-images.githubusercontent.com/44868400/222840716-10c27091-db04-42f8-8e05-53c4b62d5b84.png)
**Setup Details (please complete the following information):**
 - Computer Model: [MacBook Pro M1 Pro 16" Late 2021]
 - OS: [macOS 12.6.2
 - DAW: [Live]
 - MIDI Interface: [USB]
 - Synth Model: [Access Virus TI2 Polar]
 - Editor Version: [e.g. 3.0.0 build 9024]
 - Main Connection: [USB]

**Comment by Kodedweb** [comment]
I have sorted it. I didn't have a patches folder on my root!

**Comment by dreammusic1357** [comment]
I have same problem , Could you tell me how you fix this ? , thanks
