### ISSUE TITLE
Build 9028, System hangs when sending single programs to Virus B

### ISSUE THREAD

**Issue by citysoundman** [AURAPluginsLtd/Access-Virus-Editor#53]
On a 2013 MacPro Mojave. Using Standalone app. When I try sending a single program from a bank to my Virus B the system hangs for a few seconds, I get the spinning ball, then eventually it sends. I reverted to 9024 and all is well now.

**Comment by JaniKervinen** [comment]
can you let me know if this issue is still present with build 9031?

**Comment by citysoundman** [comment]
Issue is resolved! Working fine, no hangs. Thanks SO much!
