### ISSUE TITLE
Midi Synchronisation 3.0.0. 9033

### ISSUE THREAD

**Issue by Jack-Maddox** [AURAPluginsLtd/Access-Virus-Editor#62]
build 9024 was rock solid in terms off midi synchronisation.
Now in 9033 it is drifting all over the place while syncing to external clock. 
I refuse to setup Virus as master clock. Will not work for me.

Please check the synchronisation for 9033.

**Comment by JaniKervinen** [comment]
Hi @Jack-Maddox 👋🏻 Sure thing. We will investigate this further.

**Comment by spinlud** [comment]
+1
Midi timing is wrong, notes being dropped or delayed randomly. Happens both in playback and while playing realtime

**Comment by Jack-Maddox** [comment]
All builds have their issues. However 9024 is midi stable, but with other issues. 
It is clear that there is no fully functional build, which is too bad……..

**Comment by CyrusandVirus** [comment]
I have a similar problem when I record midi from a keyboard. Nothing compares to a file drawn in piano roll.

my example:
https://drive.google.com/file/d/1d_jDfaMOKzYUnuwuzQrg1RwTLPBkc72l/view?usp=share_link

**Comment by TOTTOR0** [comment]
Same issue with the latest version: 3.0.0 build 9033 | 2023-Mar-13
https://youtu.be/MzkTFj62CC8

Virus TI 2 / Cubase 12.0.52 / macOS 13.2.1
