### ISSUE TITLE
3.0.0.9033: midi timing all wrong

### ISSUE THREAD

**Issue by spinlud** [AURAPluginsLtd/Access-Virus-Editor#66]
**Describe the bug**
Wrong midi timing when playing notes, both in realtime and during playback.

**To Reproduce**
Just play.

**Expected behavior**
Midi timing right.

**Screenshots / Videos**
I have a done a test comparison with a simple midi clip, sending notes to Virus and to Zebra VST. The timing issue is evident.
![Screenshot 2023-04-15 at 21 37 19](https://user-images.githubusercontent.com/12783208/232250049-588d7f44-cd49-491d-ae20-ce23c2d73ede.png)

[audio tests.zip](https://github.com/AURAPluginsLtd/Access-Virus-Editor/files/11240462/audio.tests.zip)

**Setup Details (please complete the following information):**
 - Macbook pro M1 pro 2021
 - OS: macOS 12.6.5 
 - DAW: Live
 - MIDI Interface: RME
 - Synth Model: Access Virus TI2 Desktop
 - Editor Version: 3.0.0.9033
 - Main Connection: MIDI

**Comment by spinlud** [comment]
@JaniKervinen any feedback on this?

**Comment by spinlud** [comment]
Up, editor is still unusable...

**Comment by TOTTOR0** [comment]
I have the same issue! 
From day 1 is always present. Virus editor is unusable this way.
Any advise would be much appreciated. 

Here's a video reproducing that same issue:
https://youtu.be/MzkTFj62CC8

**Comment by spinlud** [comment]
Up

**Comment by JohnPh47** [comment]
Is there any news on this issue?

**Comment by TOTTOR0** [comment]
Please prioritize that kind of issues!  
We have purchased this plugin without being able of using it...

Thank you

**Comment by Avishayhz** [comment]
Did you configure everything correctly ?! Used midi ox, created virtual midi ports with loop midi as described in the manual ?
https://www.youtube.com/watch?v=_QqlmD-uWG4&t=507s
