### ISSUE TITLE
User Arpegiator separated Locking from pattern section 

### ISSUE THREAD

**Issue by Avishayhz** [AURAPluginsLtd/Access-Virus-Editor#68]
in the last version, it is almost impossible to random the arp without getting a chaos seq
please set a separated lock for the user arpgiator section.

That way, you can random the sequencer without randomizing the tempo or the pattern type .. Very useful !! 

The virus TI plugin editor from access does it a lot better than this editor which is a pity, because this editor seems to work 
perfectly with all the other stuff.

**Comment by JaniKervinen** [comment]
I will be adding this one in!

**Comment by JaniKervinen** [comment]
and done. coming up in next release

**Comment by Avishayhz** [comment]
This was quick :)

**Comment by JaniKervinen** [comment]
<img width="1400" alt="image" src="https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/46903303/5afced4d-9ffd-4fab-ae05-9fead70d8946">

not the best placing of locks but there's no more room available :/

**Comment by Avishayhz** [comment]
I would put it in the menu .. if you can initialize part .. you can also close all lock part

**Comment by JaniKervinen** [comment]
https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/46903303/d5d6b84c-4139-4f74-9b2e-e3b11c46e29a

**Comment by Avishayhz** [comment]
Beautiful actually
