### ISSUE TITLE
after randomizing the Arp section, section freezes 

### ISSUE THREAD

**Issue by Avishayhz** [AURAPluginsLtd/Access-Virus-Editor#69]
random only the arpegiator page 
try to edit the user sequncer -> Fail ! Bug !!

**Comment by JaniKervinen** [comment]
ok going to check this out today as well. but now it's time for some shut eye =)

**Comment by Avishayhz** [comment]
Thank you so much Jani. the button also in the preset section or ARP on off needs sometimes to be clicked twice until they react. Don't have a clue. Maybe this is a edit buffer thing. Idk.

**Comment by Avishayhz** [comment]
Load a preset with arpegietor then toggle the ARP off.. it won't turn off.. set it to on then off .. the ARP turns off.

**Comment by JaniKervinen** [comment]
ok I see. I will do the tests and fix it
