### ISSUE TITLE
Mod Matrix selection bug

### ISSUE THREAD

**Issue by James-Hamilton-zefr** [AURAPluginsLtd/Access-Virus-Editor#71]
**Describe the bug**
Via the LFO/MOD MATRIX it is not possible to select OSC 1 pulse/width or Shape/index. Same goes for OSC 2. You cannot select pulse/width or shape/index. Selecting from the device it self is still possible and shows the correct selection in the VST editor.

**To Reproduce**
1. Navigate to LFO/MOD MATRIX
2. Under any of the 6 mod slots attempt to select osc 1 shape/index from the drop down.
3. repeat for pulse/width and OSC 2 pulse/width and shape/index

**Expected behavior**
If you repeat the steps above once you click on OSC 1 shape/index the drop down will close but OCS 1 shape/index or any of the other 3 i mention will not be selected in the box.

**Screenshots / Videos**
before click:
<img width="390" alt="Screenshot 2023-06-13 at 10 50 49 PM" src="https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/47675225/810c0ba6-cabb-4e91-8968-5ac0e966dfc2">
after click:
<img width="308" alt="Screenshot 2023-06-13 at 10 50 54 PM" src="https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/47675225/f3e6a123-fce4-4326-932f-2e42330ef59c">

**Setup Details (please complete the following information):**
 - Computer Model: [e.g. Custom PC, MacBook Pro M1 Pro 16" Late 2021]
 - OS: [ macOS 13.3.1 ]
 - DAW: [ Ableton Live 11.3 ]
 - MIDI Interface: [ USB Direct to computer ]
 - Synth Model: [ Access Virus TI2 Desktop ]
 - Editor Version: [e.g. 3.0.0 build 9645]
 - Main Connection: [ USB ]

**Additional context**

**Comment by JaniKervinen** [comment]
done, fix coming up in next release
