### ISSUE TITLE
'Overwrite bank' creates new bank

### ISSUE THREAD

**Issue by Christian-548376** [AURAPluginsLtd/Access-Virus-Editor#74]
Hallo,

I have my patches/banks in a separate folder (My RAM-D, see screen), but when modify/save the bank (My Arp Bank) and select 'Overwrite bank' from Bank Edit it creates a new bank in the 'main' folder. (see screen). This happens in the VST3 and standalone version.

<img width="782" alt="Overwrite Bank" src="https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/136122436/e2b63103-4fef-408f-a225-67c486709141">

**To Reproduce**
See above

**Expected behavior**
It should overwrite the bank in the folder and not create a new one...

**Screenshots / Videos**
attached...

**Setup Details (please complete the following information):**
 - Computer Model: iMac Retina 5K 2019
 - OS: macOS 13.4 Ventura
 - DAW: Live
 - MIDI Interface: ESI MidiMate eX
 - Synth Model: Access Virus TI Keyboard
 - Editor Version: 3.0.0 build 9033
 - Main Connection: MIDI (no USB to TI)

**Comment by JaniKervinen** [comment]
ok I will check this if it something to do with the path not properly being adopted to sub folders
