### ISSUE TITLE
FX reverb knobs can not be selected

### ISSUE THREAD

**Issue by Christian-548376** [AURAPluginsLtd/Access-Virus-Editor#75]
**Describe the bug**
(1)
In _Extented Mixer View active_ (see screen) the FX reverb knobs can not be selected in the Editor window, but the _key range_ (from the normal editor screen ) is shown. The FX knobs changed from the hardware are shown/updated in the Editor window.

(2)
The _tool tips_ are also wrong (shown from _key range_) when hovering over the _FX reverb_ knobs.

(3)
The _part buttons_ can (sometimes) not made active in the _Multimode Mixer_ when licked on it (in the _Patch Lib_ it works fine.). Parts selected from the hardware are shown/updated in the editor window.

<img width="1493" alt="Screen 1" src="https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/136122436/3fe31600-e7d1-45a6-9285-97f675c9e908">

Setup Details 
Computer Model: iMac Retina 5K 2019
OS: macOS 13.4 Ventura
DAW: Live
MIDI Interface: ESI MidiMate eX
Synth Model: Access Virus TI Keyboard
Editor Version: 3.0.0 build 9033
Main Connection: MIDI (no USB to TI)

**Comment by Avishayhz** [comment]
seems like the button for the key range are not hidden .. wanted to report this as well

**Comment by JaniKervinen** [comment]
yep, this is sorted and coming up with next release

**Comment by Avishayhz** [comment]
Thank you!!
