### ISSUE TITLE
Close all the locks

### ISSUE THREAD

**Issue by Avishayhz** [AURAPluginsLtd/Access-Virus-Editor#78]
**Is your feature request related to a problem? Please describe.**
the locking are always set to open. There is no way to close them all and go one by one to random the effects. If they are all open and one clicks the button the chances of getting a decent sound is almost none existing  

**Describe the solution you'd like**
individual sections randomize buttons instead of the locks

**Describe alternatives you've considered**
button to close all the locks. There is one to release all. 

**Additional context**
the arpaggiator should have also 3 separated buttons to randomize velocity, step, length or 3 locks

**Comment by analogmonster** [comment]
I second this request, a way to lock them all at once would be useful, as would randomise only a particular section

**Comment by analogmonster** [comment]
To answer this a little, I just found something that is close to the feature request.  Open plugin interface, go to Utilities - Editor Preferences - tick Randomize Tab Content Only.  Then if you want to eg. randomise just the filter, you only have to lock the Oscillators, Mixer, Envelope and Amplifier and be on that tab when you hit randomise.  LFO, FX and Arp won't be randomized unless you are on those tabs

**Comment by Avishayhz** [comment]
Well, this feature was my Idee back then.
You can do this but it is exhausting ❤️

I think the best way would be maybe a (R) next to the each lock .. that way you can fine tune everything easier 
You don't even need this locks actually anymore
Would be Soo glad to see them removed and replaced.

**Comment by JaniKervinen** [comment]
hmm yeah I could add lock all function too. what if, part lock button is toggled on it would toggle all locks for the set part and also unlocking part lock would release all locks from set part?

with part lock button i mean the lock button next to part patch name (mini mixer view)

**Comment by JaniKervinen** [comment]
actually, that is what i'm gonna do right now as it makes the most sense anyway

**Comment by JaniKervinen** [comment]
done, coming up with next release
