### ISSUE TITLE
Patch Librarian not sending patches to Virus TI2

### ISSUE THREAD

**Issue by neonrecursion** [AURAPluginsLtd/Access-Virus-Editor#79]
I am using Mac Monterey, Virus HE 3.0.0 with a midiplus 2x2 mac device on an iMac Pro.

I have been able to get the device connected. I also got the proper message from Sync Data from HW. Everything seems to be working. Similarly, if I tweak a cutoff knob, no issues.

Where things are screwy is the patch librarian. If I double-click a name, it will show up on the left side in part 1 (I am using part 1 for this example). The Virus itself will act as if nothing is changed. If I use the + and - buttons next to part 1, I can get the patches to change on the Virus TI2 but they never seem to match the Editor version. 

So the issue is basically that the editor will not send patches to the Virus via choosing the names in the editor, only via pressing + or - in the editor or directly on the device. 

I have set the settings on the Virus T12 as per the instruction manual for the editor.

**Comment by JaniKervinen** [comment]
ok i will investigate this during the next couple of days and have it fixed. in the meanwhile, you can catch us up at discord :)

**Comment by JaniKervinen** [comment]
This is sorted now! Coming up in next release

**Comment by neonrecursion** [comment]
Thanks!!
