### ISSUE TITLE
Midi port assign for the pluging at startup

### ISSUE THREAD

**Issue by Avishayhz** [AURAPluginsLtd/Access-Virus-Editor#80]
**Is your feature request related to a problem? Please describe.**
Every time the plugin start, I assign the same midi port.

**Describe the solution you'd like**
save midi port and assign automatically on restart

**Describe alternatives you've considered**
remove the assign Bar and use a menu for it. Plugin settings. That way, the schema will be saved automatically.
No need to for settings every time. You can use a hide function in case someone is using multiple synths. Because this is just for people with one virus device.

**Comment by JaniKervinen** [comment]
You can achieve this by saving your favorite settings with "save ui data" if i do remember correctly. Then load the ui data once editor is open. it is safer option considering all different platforms (vst, vst3, au, aax) and the graphics themselves.

Would that be enough?

I tried saving the midi i/o back in the days to midi file, but it caused all kinds of havoc. I could do it again with a lot more knowledge than previously (mainly not causing crash if device is not present...) Could add option in utilities menu to save default midi i/o (for those who have one virus)?

**Comment by Avishayhz** [comment]
Yes. And option would be perfect. Then you could even hide all the settings bar at the top of selected. Idk. Seems easier then loading a new template, when the plugin starts. Actually you can make also .. load preset on startup. That way you can also get the standard behavior of the access plugin.

**Comment by Avishayhz** [comment]
Certainly easier !! No need I think to change the default.. just a possibility to set/unset it would be great.

**Comment by JaniKervinen** [comment]
ok i'll drop this in today - beta will be published in discord (are you in there already?)

**Comment by Avishayhz** [comment]
Yes
