### ISSUE TITLE
Oscillator 3 level locking

### ISSUE THREAD

**Issue by analogmonster** [AURAPluginsLtd/Access-Virus-Editor#81]
**Describe the bug**
Bug in lock/randomize.  Oscillator 3 level doesn't lock

**To Reproduce**
1. Lock mixer 
2. don't lock oscillators
3. randomize 

**Expected behavior**
Oscillator 3 level should stay at previous level setting if mixer is locked.  I understand that level will automatically be zero if oscillator 3 is inactive and a certain level if it is active.  Lets say it is set to 127 before randomization.  The behaviour should be to remember the previously set level if oscillator 3 is changed from active to inactive (still grey it out/set to zero when inactive), but if randomising a second time changes oscillator 3 back to active, it should return to 127.

**Screenshots / Videos**
None

**Setup Details (please complete the following information):**
 - Computer Model: Mac Pro late 2013
 - OS: macOS 11.7.9 (Big Sur)
 - DAW: Ableton Live 11.3.4
 - MIDI Interface: MOTU MIDI express 128
 - Synth Model: Access Virus TI Desktop
 - Editor Version: 3.0.0 build 9033
 - Main Connection: MIDI interface and audio interface

**Additional context**

**Comment by JaniKervinen** [comment]
fixed. coming up in next release

**Comment by analogmonster** [comment]
Great news thanks
