### ISSUE TITLE
Empty preset banks (.mid files) not listed in Patch Librarian browser menu

### ISSUE THREAD

**Issue by o-z-o-n** [AURAPluginsLtd/Access-Virus-Editor#83]
Any preset/patch bank (.mid file) which is empty, as originally created by the Virus TI Plugin, is not visible in the Patch Librarian browser menu.

**To Reproduce**
1. Create empty preset bank file
2. Put file in Patches folder
3. Bank Edit -> Refresh Folders
4. Empty bank does not appear

**Expected behavior**
Empty banks should also appear in the Patch Librarian Menu for selection.

**Screenshots / Videos**
Several "ROM Favorites" are missing, for example "ROM Favorites P": 
![Virus Editor missing empty libraries 2023-09-09](https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/144550227/8a00cb7c-8e98-42da-a7e4-6a011f31f232)

**Setup Details (please complete the following information):**
 - Computer Model: Mac mini 2018, 3.2GHz i7, 64GB RAM, 2TB SSD
 - OS: macOS 13.5.1 (Ventura)
 - DAW: Cubase / Standalone Editor
 - MIDI Interface: none / Aura USB MIDI driver
 - Synth Model:Access Virus TI2 Darkstar
 - Editor Version: 3.0.0 build 9033
 - Main Connection: USB

**Additional context**
See attached ROM Favorites folder which contains several empty library files.
[ROM Favorites.zip](https://github.com/AURAPluginsLtd/Access-Virus-Editor/files/12566252/ROM.Favorites.zip)

**Comment by JaniKervinen** [comment]
done and coming up in next release
