### ISSUE TITLE
Search only finds results in selected bank

### ISSUE THREAD

**Issue by o-z-o-n** [AURAPluginsLtd/Access-Virus-Editor#84]
**Describe the bug**
The search by text only finds results in the currently selected bank which is visible/active in the lower section of the Patch Librarian.

**To Reproduce**
1. Select Virus TI2 Rom A.mid
2. Search for "BC"
3. Result lists 19 presets
4. "ArpAcid BC" from bank Rom B is not listed

**Expected behavior**
The search should list results from all banks stored in the Patches folder. It should find all presets e.g. by Ben Cosling (BC), regardless of where they are stored. This is the known and expected behavior of the original Virus TI Plugin.

**Screenshots / Videos**
If applicable, add screenshots to help explain your problem. Videos do magic too!

![Bildschirmfoto 2023-09-09 um 18 55 50](https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/144550227/95d89eb4-6480-424f-a152-bb115feb667d)
![Bildschirmfoto 2023-09-09 um 18 55 32](https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/144550227/c26842a4-eb9a-40a0-bb69-ed6ac2a22d47)
![Bildschirmfoto 2023-09-09 um 18 56 03](https://github.com/AURAPluginsLtd/Access-Virus-Editor/assets/144550227/29f74ae9-bb44-4c03-ab5b-47c8640c6265)

**Setup Details (please complete the following information):**
 - Computer Model: Mac mini 2018, 3.2GHz i7, 64GB RAM, 2TB SSD
 - OS: macOS 13.5.1 (Ventura)
 - DAW: Cubase / Standalone Editor
 - MIDI Interface: none / Aura USB MIDI driver
 - Synth Model:Access Virus TI2 Darkstar
 - Editor Version: 3.0.0 build 9033
 - Main Connection: USB

**Additional context**

**Comment by JaniKervinen** [comment]
utilities menu -> editor preferences (librarian preferences in upcoming version) -> check or uncheck search active bank and or search contains to allow broader results.
works already in existing version.
