### ISSUE TITLE
Patch Librarian search without result problems

### ISSUE THREAD

**Issue by o-z-o-n** [AURAPluginsLtd/Access-Virus-Editor#85]
**Describe the bug**
A Patch Librarian search without any hits:
- does not display an empty search result
- immediately replaces the search term with "search..."

**To Reproduce**
1. Switch to Patch Librarian mode
2. Activate search (click magnifying glass)
3. Enter a search term that will not find any matching presets
4. Hit enter

**Expected behavior**
The behavior should be equivalent to a successful search. The (emtpy) result should be shown in the lower library section, and the  search term should be displayed as entered. It therefore should be possible to execute the same search after selecting a different bank.

**Screenshots / Videos**
If applicable, add screenshots to help explain your problem. Videos do magic too!

**Setup Details (please complete the following information):**
 - Computer Model: Mac mini 2018, 3.2GHz i7, 64GB RAM, 2TB SSD
 - OS: macOS 13.5.1 (Ventura)
 - DAW: Cubase / Standalone Editor
 - MIDI Interface: none / Aura USB MIDI driver
 - Synth Model:Access Virus TI2 Darkstar
 - Editor Version: 3.0.0 build 9033
 - Main Connection: USB

**Additional context**

**Comment by JaniKervinen** [comment]
done. coming up with next release
