### ISSUE TITLE
Search text I-beam cursor kills bank selector +/- switches

### ISSUE THREAD

**Issue by o-z-o-n** [AURAPluginsLtd/Access-Virus-Editor#86]
**Describe the bug**
In the Patch Librarian mode: When clicking on one of the bank selector [+] or [-] switches while the cursor is active for search text entry, the bank selector switches become unusable.

**To Reproduce**
1. Switch to Patch Librarian mode 
2. Activate preset search (click magnifying glass)
3. Click in search field (cursor changes from pointer to text entry "I-beam")
4. Click on the [+] or [-] button to switch the bank for the lower section of the Patch Librarian.
5. Deactivate search
6. Click on the [+] or [-] button to switch the bank for the lower section of the Patch Librarian --> nothing happens

**Expected behavior**
After leaving the search mode, bank selector switches should always work regardless of what was clicked during the search.

**Screenshots / Videos**
If applicable, add screenshots to help explain your problem. Videos do magic too!

**Setup Details (please complete the following information):**
 - Computer Model: Mac mini 2018, 3.2GHz i7, 64GB RAM, 2TB SSD
 - OS: macOS 13.5.1 (Ventura)
 - DAW: Cubase / Standalone Editor
 - MIDI Interface: none / Aura USB MIDI driver
 - Synth Model:Access Virus TI2 Darkstar
 - Editor Version: 3.0.0 build 9033
 - Main Connection: USB

**Additional context**

**Comment by JaniKervinen** [comment]
done. coming up in next release
